export { default as arrowRight } from './arrow-right'
export { default as checkmark } from './checkmark'
export { default as discord } from './discord'
export { default as arrowDown } from './arrow-down'
export { default as slideLeft } from './slide-left'
export { default as slideRight } from './slide-right'
export { default as list } from './list'
export { default as close } from './close'
